/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthReceiver } from "./EthReceiver";
export type { OnlyWethReceiver } from "./OnlyWethReceiver";
export type { PermitAndCall } from "./PermitAndCall";
