/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { TimeLockHook, TimeLockHookInterface } from "../TimeLockHook";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "preInteraction",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610300806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80635d8b0f8414610030575b600080fd5b61004a60048036038101906100459190610176565b61004c565b005b6000828281019061005d9190610220565b9050804210156100a2576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610099906102aa565b60405180910390fd5b5050505050565b600080fd5b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100de826100b3565b9050919050565b6100ee816100d3565b81146100f957600080fd5b50565b60008135905061010b816100e5565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f84011261013657610135610111565b5b8235905067ffffffffffffffff81111561015357610152610116565b5b60208301915083600182028301111561016f5761016e61011b565b5b9250929050565b600080600080606085870312156101905761018f6100a9565b5b600061019e878288016100fc565b94505060206101af878288016100fc565b935050604085013567ffffffffffffffff8111156101d0576101cf6100ae565b5b6101dc87828801610120565b925092505092959194509250565b6000819050919050565b6101fd816101ea565b811461020857600080fd5b50565b60008135905061021a816101f4565b92915050565b600060208284031215610236576102356100a9565b5b60006102448482850161020b565b91505092915050565b600082825260208201905092915050565b7f54696d65206e6f74207265616368656420796574000000000000000000000000600082015250565b600061029460148361024d565b915061029f8261025e565b602082019050919050565b600060208201905081810360008301526102c381610287565b905091905056fea2646970667358221220cbab725025cbd2a14896af8c0145f5bd0bccd009d37a75a48482252e577eac4764736f6c63430008140033";

type TimeLockHookConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TimeLockHookConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TimeLockHook__factory extends ContractFactory {
  constructor(...args: TimeLockHookConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TimeLockHook> {
    return super.deploy(overrides || {}) as Promise<TimeLockHook>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): TimeLockHook {
    return super.attach(address) as TimeLockHook;
  }
  override connect(signer: Signer): TimeLockHook__factory {
    return super.connect(signer) as TimeLockHook__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TimeLockHookInterface {
    return new utils.Interface(_abi) as TimeLockHookInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TimeLockHook {
    return new Contract(address, _abi, signerOrProvider) as TimeLockHook;
  }
}
