/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDaiLikePermit } from "./IDaiLikePermit";
export type { IERC20MetadataUppercase } from "./IERC20MetadataUppercase";
export type { IERC7597Permit } from "./IERC7597Permit";
export type { IPermit2 } from "./IPermit2";
export type { IWETH } from "./IWETH";
