/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ERC721ProxySafeInterface extends Interface {
  getFunction(
    nameOrSignature: "IMMUTABLE_OWNER" | "func_60iHVgK"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "IMMUTABLE_OWNER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "func_60iHVgK",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "IMMUTABLE_OWNER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "func_60iHVgK",
    data: BytesLike
  ): Result;
}

export interface ERC721ProxySafe extends BaseContract {
  connect(runner?: ContractRunner | null): ERC721ProxySafe;
  waitForDeployment(): Promise<this>;

  interface: ERC721ProxySafeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IMMUTABLE_OWNER: TypedContractMethod<[], [string], "view">;

  func_60iHVgK: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      arg2: BigNumberish,
      tokenId: BigNumberish,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IMMUTABLE_OWNER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "func_60iHVgK"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      arg2: BigNumberish,
      tokenId: BigNumberish,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
