/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  BitInvalidatorLib,
  BitInvalidatorLibInterface,
} from "../../../contracts/libraries/BitInvalidatorLib";

const _abi = [
  {
    inputs: [],
    name: "BitInvalidatedOrder",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220b7ab25d266c918feab0de4a6277756a340aa1c4f72ea7feaa2c993ca7089de4064736f6c63430008170033";

type BitInvalidatorLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BitInvalidatorLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BitInvalidatorLib__factory extends ContractFactory {
  constructor(...args: BitInvalidatorLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BitInvalidatorLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BitInvalidatorLib__factory {
    return super.connect(runner) as BitInvalidatorLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BitInvalidatorLibInterface {
    return new Interface(_abi) as BitInvalidatorLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BitInvalidatorLib {
    return new Contract(address, _abi, runner) as unknown as BitInvalidatorLib;
  }
}
