/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  OffsetsLib,
  OffsetsLibInterface,
} from "../../../contracts/libraries/OffsetsLib";

const _abi = [
  {
    inputs: [],
    name: "OffsetOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212202b4a5b73f74003f08eecea320d5af8896c6f64ebe0aceac6b4605d1ced7b9aa464736f6c63430008170033";

type OffsetsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OffsetsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OffsetsLib__factory extends ContractFactory {
  constructor(...args: OffsetsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      OffsetsLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): OffsetsLib__factory {
    return super.connect(runner) as OffsetsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OffsetsLibInterface {
    return new Interface(_abi) as OffsetsLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): OffsetsLib {
    return new Contract(address, _abi, runner) as unknown as OffsetsLib;
  }
}
