/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  GuardManager,
  GuardManagerInterface,
} from "../../../../../../@gnosis.pm/safe-contracts/contracts/base/GuardManager.sol/GuardManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "guard",
        type: "address",
      },
    ],
    name: "ChangedGuard",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "guard",
        type: "address",
      },
    ],
    name: "setGuard",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100165761010b908161001c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c63e19a9dd914602857600080fd5b3460d157602036600319011260d1576004356001600160a01b0381169182820360cd5730330360a357507f1151116914515bc0891ff9047a6cb32cf902546f83066499bcf8ba33d2353fa2916020917f4a204f620c8c5ccdca3fd54d003badd85ba500436a431f0cbda4f558c93c34c855604051908152a180f35b62461bcd60e51b8152602060048201526005602482015264475330333160d81b6044820152606490fd5b8380fd5b5080fdfea2646970667358221220f7edcc955bbca56b1ff8131903bf969635836d2179f22728c0bcbaa52aabecc364736f6c63430008170033";

type GuardManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GuardManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GuardManager__factory extends ContractFactory {
  constructor(...args: GuardManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GuardManager & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GuardManager__factory {
    return super.connect(runner) as GuardManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GuardManagerInterface {
    return new Interface(_abi) as GuardManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GuardManager {
    return new Contract(address, _abi, runner) as unknown as GuardManager;
  }
}
