/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOrderMixin {
  export type OrderStruct = {
    salt: BigNumberish;
    maker: BigNumberish;
    receiver: BigNumberish;
    makerAsset: BigNumberish;
    takerAsset: BigNumberish;
    makingAmount: BigNumberish;
    takingAmount: BigNumberish;
    makerTraits: BigNumberish;
  };

  export type OrderStructOutput = [
    salt: bigint,
    maker: bigint,
    receiver: bigint,
    makerAsset: bigint,
    takerAsset: bigint,
    makingAmount: bigint,
    takingAmount: bigint,
    makerTraits: bigint
  ] & {
    salt: bigint;
    maker: bigint;
    receiver: bigint;
    makerAsset: bigint;
    takerAsset: bigint;
    makingAmount: bigint;
    takingAmount: bigint;
    makerTraits: bigint;
  };
}

export declare namespace SafeOrderBuilder {
  export type OracleQueryParamsStruct = {
    oracle: AddressLike;
    originalAnswer: BigNumberish;
    ttl: BigNumberish;
  };

  export type OracleQueryParamsStructOutput = [
    oracle: string,
    originalAnswer: bigint,
    ttl: bigint
  ] & { oracle: string; originalAnswer: bigint; ttl: bigint };
}

export interface SafeOrderBuilderInterface extends Interface {
  getFunction(nameOrSignature: "buildAndSignOrder"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buildAndSignOrder",
    values: [
      IOrderMixin.OrderStruct,
      BytesLike,
      SafeOrderBuilder.OracleQueryParamsStruct,
      SafeOrderBuilder.OracleQueryParamsStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "buildAndSignOrder",
    data: BytesLike
  ): Result;
}

export interface SafeOrderBuilder extends BaseContract {
  connect(runner?: ContractRunner | null): SafeOrderBuilder;
  waitForDeployment(): Promise<this>;

  interface: SafeOrderBuilderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buildAndSignOrder: TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      extension: BytesLike,
      makerAssetOracleParams: SafeOrderBuilder.OracleQueryParamsStruct,
      takerAssetOracleParams: SafeOrderBuilder.OracleQueryParamsStruct
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buildAndSignOrder"
  ): TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      extension: BytesLike,
      makerAssetOracleParams: SafeOrderBuilder.OracleQueryParamsStruct,
      takerAssetOracleParams: SafeOrderBuilder.OracleQueryParamsStruct
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
