/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  EthReceiver,
  EthReceiverInterface,
} from "../../../../../@1inch/solidity-utils/contracts/mixins/EthReceiver";

const _abi = [
  {
    inputs: [],
    name: "EthDepositRejected",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class EthReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): EthReceiverInterface {
    return new Interface(_abi) as EthReceiverInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): EthReceiver {
    return new Contract(address, _abi, runner) as unknown as EthReceiver;
  }
}
