/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  OnlyWethReceiver,
  OnlyWethReceiverInterface,
} from "../../../../../@1inch/solidity-utils/contracts/mixins/OnlyWethReceiver";

const _abi = [
  {
    inputs: [],
    name: "EthDepositRejected",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class OnlyWethReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): OnlyWethReceiverInterface {
    return new Interface(_abi) as OnlyWethReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OnlyWethReceiver {
    return new Contract(address, _abi, runner) as unknown as OnlyWethReceiver;
  }
}
