/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPermit2WitnessTransferFrom,
  IPermit2WitnessTransferFromInterface,
} from "../../../contracts/interfaces/IPermit2WitnessTransferFrom";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPermit2WitnessTransferFrom.TokenPermissions",
            name: "permitted",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
        ],
        internalType: "struct IPermit2WitnessTransferFrom.PermitTransferFrom",
        name: "permit",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "requestedAmount",
            type: "uint256",
          },
        ],
        internalType:
          "struct IPermit2WitnessTransferFrom.SignatureTransferDetails",
        name: "transferDetails",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "witness",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "witnessTypeString",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "permitWitnessTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPermit2WitnessTransferFrom__factory {
  static readonly abi = _abi;
  static createInterface(): IPermit2WitnessTransferFromInterface {
    return new Interface(_abi) as IPermit2WitnessTransferFromInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPermit2WitnessTransferFrom {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPermit2WitnessTransferFrom;
  }
}
