/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ILimitOrderProtocolInterface extends utils.Interface {
  functions: {
    "fillOrder(bytes,bytes,uint256,bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "fillOrder"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "fillOrder",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "fillOrder", data: BytesLike): Result;

  events: {};
}

export interface ILimitOrderProtocol extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILimitOrderProtocolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    fillOrder(
      order: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      makingAmount: PromiseOrValue<BigNumberish>,
      interaction: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  fillOrder(
    order: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    makingAmount: PromiseOrValue<BigNumberish>,
    interaction: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    fillOrder(
      order: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      makingAmount: PromiseOrValue<BigNumberish>,
      interaction: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    fillOrder(
      order: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      makingAmount: PromiseOrValue<BigNumberish>,
      interaction: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fillOrder(
      order: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      makingAmount: PromiseOrValue<BigNumberish>,
      interaction: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
