/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILimitOrderProtocol,
  ILimitOrderProtocolInterface,
} from "../../CustomMatcher.sol/ILimitOrderProtocol";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "order",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "makingAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "interaction",
        type: "bytes",
      },
    ],
    name: "fillOrder",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ILimitOrderProtocol__factory {
  static readonly abi = _abi;
  static createInterface(): ILimitOrderProtocolInterface {
    return new utils.Interface(_abi) as ILimitOrderProtocolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILimitOrderProtocol {
    return new Contract(address, _abi, signerOrProvider) as ILimitOrderProtocol;
  }
}
