/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITimeLockHook,
  ITimeLockHookInterface,
} from "../../CustomMatcher.sol/ITimeLockHook";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "taker",
        type: "address",
      },
      {
        internalType: "address",
        name: "maker",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "preInteraction",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITimeLockHook__factory {
  static readonly abi = _abi;
  static createInterface(): ITimeLockHookInterface {
    return new utils.Interface(_abi) as ITimeLockHookInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITimeLockHook {
    return new Contract(address, _abi, signerOrProvider) as ITimeLockHook;
  }
}
