/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CustomMatcher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CustomMatcher__factory>;
    getContractFactory(
      name: "ILimitOrderProtocol",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILimitOrderProtocol__factory>;
    getContractFactory(
      name: "ITimeLockHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimeLockHook__factory>;
    getContractFactory(
      name: "TimeLockHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimeLockHook__factory>;

    getContractAt(
      name: "CustomMatcher",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CustomMatcher>;
    getContractAt(
      name: "ILimitOrderProtocol",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILimitOrderProtocol>;
    getContractAt(
      name: "ITimeLockHook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ITimeLockHook>;
    getContractAt(
      name: "TimeLockHook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TimeLockHook>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
